version: '3'

networks:
  laravel:

services:
  site:
    build:
      context: ./dockerfiles
      dockerfile: nginx.dockerfile
    container_name: nginx
    ports:
      - 8088:80
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php
      - redis
      # - mysql
      - postgres
      - mailhog
    networks:
      - laravel
  
  # mysql:
  #   image: mariadb:10.7
  #   container_name: mysql
  #   restart: unless-stopped
  #   tty: true
  #   ports:
  #     # - 3306:3306
  #     - 4306:3306
  #   volumes:
  #     - ./dockerfiles/mysql:/var/lib/mysql
  #   environment:
  #     MYSQL_DATABASE: laravel-docker
  #     MYSQL_USER: admin
  #     MYSQL_PASSWORD: admin
  #     MYSQL_ROOT_PASSWORD: sa
  #     SERVICE_TAGS: dev
  #     SERVICE_NAME: mysql
  #   networks:
  #     - laravel

  postgres:
    image: postgres:14.3
    container_name: postgres
    restart: unless-stopped
    tty: true
    ports:
      - 5432:5432
    volumes:
      - ./dockerfiles/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    networks:
      - laravel

  php:
    build: 
      context: ./dockerfiles
      dockerfile: php.dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      # - 6379:6379
      - 7379:6379
    networks:
      - laravel

  composer:
    image: composer:2.3
    container_name: composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    user: root
    entrypoint: ['composer', '--ignore-platform-reqs']
    networks:
      - laravel

  npm:
    image: node:16
    container_name: npm
    volumes:
      - ./src:/var/www/html
    ports:
      - 3000:3000
      - 3001:3001
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
      - laravel
  
  artisan:
    build: 
      context: ./dockerfiles
      dockerfile: php.dockerfile
    container_name: artisan
    volumes:
      - ./src:/var/www/html
    depends_on:
      # - mysql
      - postgres
    working_dir: /var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
    networks:
      - laravel
  
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - laravel